version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: popcorn-palace
      POSTGRES_PASSWORD: popcorn-palace
      POSTGRES_DB: popcorn-palace
    ports:
      - "5432:5432"
    networks:
      - app-network

  app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: popcorn-palace
      DB_PASSWORD: popcorn-palace
      DB_DATABASE: popcorn-palace
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
